### ISSUE TITLE
How to use /vsizip/ and /vsigzip/?

### ISSUE THREAD

**Issue by TimJMartin** [naturalatlas/node-gdal#125] opened 2015-10-09 12:21 UTC
Another basic question (sorry!)

Looking at the codebase I can see that /vsizip/ and /vsigzip/ are in there but am really struggling to use them. I keep getting: error opening dataset.

I have tried the following permutations

```
var dataset = gdal.open('/vsigzip/hp40ne.gz')
var dataset = gdal.open('vsigzip/hp40ne.gz/hp40ne')
var dataset = gdal.open('/vsigzip/hp40ne.gz/, 'r', 'GML')
```

There is even this entry in the ogrgml driver regarding the data I am trying to read:
```js
/* Might be a OS-Mastermap gzipped GML, so let be nice and try to open */
    /* it transparently with /vsigzip/ */
    else
    if ( poOpenInfo->pabyHeader[0] == 0x1f && poOpenInfo->pabyHeader[1] == 0x8b &&
         EQUAL(CPLGetExtension(poOpenInfo->pszFilename), "gz") &&
         strncmp(poOpenInfo->pszFilename, "/vsigzip/", strlen("/vsigzip/")) != 0 )
    {
        return -1; /* must be later checked */
    }
```
This made me think maybe I just needed to do
```js
var dataset = gdal.open('hp40ne.gz') 
```
But this gave me the same error opening message.

Sorry for such a novice question ;)

**Comment by brandonreavis** [comment] 2015-10-09 16:43
Here is a basic guide to using `/vsizip/` and `/vsigzip/` : http://erouault.blogspot.com/2012/05/new-gdal-virtual-file-system-to-read.html

I think the problem you have is that you need to specify where there file is in the zip that you want to open:
```js
gdal.verbose(); //this will print out a more detailed error message to the console which will help debugging
var ds = gdal.open('/vsigzip/hp40ne.gz/path/to/file');
```

**Comment by TimJMartin** [comment] 2015-10-09 17:46
@brandonreavis 

Thanks for the reply. Sorry should I have said that already use both /vsizip/ and /vsigzip/ in my python scripts with ogr2ogr but am struggling to migrate my code to Node. 

I worked it our previously that if your zip or gzip only has a single file then you can just provide the path to the zip/gzip file. If there are more files in it then yes you are correct you need to add the actual filename to the full path.

However I have tried both and still no joy. I have added gdal.versbose and here is the output:

                                return open.apply(gdal, arguments);
                                            ^
Error: Error opening dataset
    at Error (native)
    at Object.open (C:\Projects\NodeExamples\NodeExamples\GDAL\node_modules\gdal\lib\gdal.js:364:17)
    at Object.<anonymous> (C:\Projects\NodeExamples\NodeExamples\GDAL\gdal_basic_cmds.js:34:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

The file I am trying can be found here if you wanted to try.

https://s3-eu-west-1.amazonaws.com/oscustomers/TJM/hp40ne.gz

Thanks for your help

**Comment by brandonreavis** [comment] 2015-10-09 18:18
Hmm weird. I tried opening it and both of these worked: 
```js
gdal.open('hp40ne.gz');
gdal.open('/vsigzip/hp40ne.gz');
```
Maybe the GML driver isnt bundled with the node-gdal that you have installed?
```js
//Does this return anything?
gdal.drivers.get('GML')
```

**Comment by TimJMartin** [comment] 2015-10-09 20:07
So it gets weirder!! so the GML driver is installed and available on my Windows 7 64bit and both attempts still failed. So I have also tried on my macbook pro.

I have Node 0.12.7 installed

I installed node-gdal using

tims-mbp:gdalVML timmartin$ npm install gdal
npm WARN installMany node-pre-gyp was bundled with gdal@0.7.1, but bundled package wasn't found in unpacked tree

> gdal@0.7.1 install /Users/timmartin/Downloads/gdalVML/node_modules/gdal
> node-pre-gyp install --fallback-to-build

[gdal] Success: "/Users/timmartin/Downloads/gdalVML/node_modules/gdal/lib/binding/gdal.node" is installed via remote
gdal@0.7.1 node_modules/gdal
├── nan@1.8.4
└── node-pre-gyp@0.6.9

This seems to have installed fine. 

My index.js code looks like this:

var gdal = require('gdal');
gdal.verbose();
var drivers = gdal.drivers.getNames();
console.log(drivers);
var ds = gdal.open('hp40ne.gz');

And this is the error log:
return open.apply(gdal, arguments);
				            ^
Error: Error opening dataset
    at Error (native)
    at Object.open (/Users/timmartin/Downloads/gdalVML/node_modules/gdal/lib/gdal.js:364:17)
    at Object.<anonymous> (/Users/timmartin/Downloads/gdalVML/index.js:5:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


What version of Node are you using for it to work?

Can you think of anything else I could try?

**Comment by BergWerkGIS** [comment] 2015-10-10 09:17
I can confirm @TimJMartin 's error messages on `Windows 7 64bit` with `node 64bit @ 0.12.7` and `node-gdal@0.7.1`.

However, if I extract the dataset from the archive and open it directly, it works.
*So, I suppose something is wrong with builtin unzip functionality on Windows/Mac.*

```js
var gdal = require('gdal');
gdal.verbose();
console.log('GML Driver: ', gdal.drivers.get('GML'));
var ds =gdal.open('hp40ne');
ds.layers.forEach(function(layer){
	console.log('----', layer.name, '----');
	console.log("     number of features: " + layer.features.count());
	console.log("     fields: " + layer.fields.getNames());
	console.log("     extent: " + JSON.stringify(layer.extent));
	console.log("     srs: " + (layer.srs ? layer.srs.toProj4() : 'null'));
});
```


```
GML Driver:  { description: 'GML' }
---- Text ----
     number of features: 104
     fields: fid,featureCode,featureDescription,anchorPosition,font,height,orientation,textString
     extent: undefined
     srs: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
---- Line ----
     number of features: 381
     fields: fid,featureCode,featureDescription
     extent: undefined
     srs: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
---- VectorMapPoint ----
     number of features: 19
     fields: fid,featureCode,featureDescription,orientation
     extent: undefined
     srs: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
---- Area ----
     number of features: 223
     fields: fid,featureCode,featureDescription
     extent: undefined
     srs: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
```

**Comment by brianreavis** [comment] 2015-10-10 18:06
My hunch is this stems from `node-gdal` not being compiled with `HAVE_LIBZ `, which affects [this](https://github.com/naturalatlas/node-gdal/blob/047e430db06bcd066a9d30ec756610e9cc3b41d6/deps/libgdal/gdal/port/cpl_vsil.cpp#L1123-L1126). I can try bundling zlib for portability. @TimJMartin do you mind if we include your file in the repo for testing, or would it be better to come up with another?

**Comment by BergWerkGIS** [comment] 2015-10-11 07:42
> My hunch is this stems from node-gdal not being compiled with HAVE_LIBZ

@brandonreavis yes, think so, too.


Interesting though, that an exception is thrown, as [an error should be returned](https://github.com/naturalatlas/node-gdal/blob/047e430db06bcd066a9d30ec756610e9cc3b41d6/deps/libgdal/gdal/port/cpl_conv.cpp#L2700-L2753).
I tried to `catch` the exception and access `gdal.lastError`, but it didn't contain anything.

> I can try bundling zlib for portability

Good idea, I also noticed that there seems to be some other zip functionality already (though I haven't looked in depth yet, if this would suffice for the `vsigzip` use case):

```
deps/libgdal/gdal/port/cpl_minizip_*.*
```
https://github.com/naturalatlas/node-gdal/tree/master/deps/libgdal/gdal/port

I will take a look at what exactly causes the crash during the next days.

**Comment by TimJMartin** [comment] 2015-10-12 08:31
hey @BergWerkGIS @brandonreavis 

Thanks for looking into this. Yes you can continue to use that data file for testing purposes.

let me know if I can help with testing

**Comment by BergWerkGIS** [comment] 2015-10-12 16:27
@TimJMartin 

**This is for `node@0.12.7 x64` on Windows.**

Could you download
https://dl.dropboxusercontent.com/u/13256369/gdal.node.7z
and replace `gdal.node` in your
```
<project-dir>\node_modules\gdal\lib\binding\
```
with the one from the archive?

Make a backup of your existing `gdal.node` just to be save.

Using `var ds =gdal.open('/vsigzip/hp40ne.gz');` I now get the same output as [above](https://github.com/naturalatlas/node-gdal/issues/125#issuecomment-147067988).

Does it work for you, too?

**Comment by BergWerkGIS** [comment] 2015-10-12 16:32
@brianreavis FYI: zlib is already bundled with gdal:
https://github.com/naturalatlas/node-gdal/tree/master/deps/libgdal/gdal/frmts/zlib

**Comment by TimJMartin** [comment] 2015-10-13 07:27
@BergWerkGIS 

Yes!!!!!!! That works.

I did a fresh install of node@0.12.7 64bit Windows, then I did a fresh install of Node-GDAL using
npm install gdal 

and then I replaced the gdal.node.

So what did you have to change?

**Comment by BergWerkGIS** [comment] 2015-10-13 07:49
@TimJMartin 
@brandonreavis was right about `HAVE_LIBZ`.

In the end (as zlib is already bundled with gdal) I just had to add to `#define HAVE_LIBZ`, although I did some serious debugging before.
Should have tried the `#define` first :smirk:

**Comment by TimJMartin** [comment] 2015-10-13 07:55
@BergWerkGIS shall i close this issue?

**Comment by BergWerkGIS** [comment] 2015-10-13 08:30
@TimJMartin 
No thanks. 
I'll do it after I've created a PR with the change and included your file into the tests.
Also curious what will happen on Linux with that change, as `/vsigzip/` worked there before already.

**Comment by BergWerkGIS** [comment] 2015-10-13 13:00
@brandonreavis PR: https://github.com/naturalatlas/node-gdal/pull/126
Curious what the `HAVE_LIBZ` does on Linux.

**Comment by BergWerkGIS** [comment] 2015-10-14 09:38
PR merged https://github.com/naturalatlas/node-gdal/pull/126

**Closed by BergWerkGIS** 2015-10-14 09:38 UTC

**Comment by pksorensen** [comment] 2017-02-09 00:13
Could we get /vsicurl/ to work also ? :)

**Comment by brianreavis** [comment] 2017-02-09 07:32
@pksorensen I can't say it's priority right now, especially given node-gdal already blocks the event loop (https://github.com/naturalatlas/node-gdal/issues/18). It'd be better to download the file using [request](https://github.com/request/request) (or whatever) and then open the file with node-gdal once it's on disk. Is that feasible, or do you have a special use case for `/vsicurl/`?

**Comment by pksorensen** [comment] 2017-02-09 09:21
/vsicurl/ is super smart. Downloading the hole file not be fiesible. 

We have 600GB og data located in a cloud storage system that supports range curries. Basically its tons of zip files with geotiffs within them. We then have vrt file binding them all together.

With vsicurl we can with one simple gdal command extract a sub region of interest without downloading 600GB of data. Ultimately it ends up only download the exact blocks from the needed filles that is needed and it performs very well. 

I was just thinking that it was some build flag or something that was missing and curl was not included like the other issue here

**Comment by timmycam** [comment] 2019-10-06 05:47
@pksorensen did you get the /vsicurl/ working with node-gdal? If you did, would you be able to share you env versions etc?
